# Generated by Django 5.1.1 on 2024-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_category', models.CharField(max_length=200)),
                ('employee_phone', models.CharField(max_length=12)),
                ('employee_dob', models.CharField(max_length=10)),
                ('employee_gender', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')])),
                ('employee_address', models.CharField(max_length=500)),
                ('employee_email', models.CharField(max_length=200)),
                ('employee_qualification', models.CharField(max_length=100)),
            ],
        ),
    ]
